# Generated by Django 4.1.5 on 2023-01-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.BigIntegerField(verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=20
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("href", models.URLField(verbose_name="URL")),
                (
                    "brand",
                    models.CharField(
                        blank=True, default="Unknown", max_length=255, null=True
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("products_id", models.TextField()),
            ],
        ),
    ]
